#!/usr/bin/env node
// Plugin validation — simulates what /materia:init materializes from the
// `materia` plugin's bundled scaffold, then verifies it. No network, no AI.
// The plugin lives at plugins/materia/: skills/ (all pipeline skills, at the
// plugin root per the Claude Code plugin spec) and scaffold/ (the MATERIA.md +
// CLAUDE.md + docs/ + check-docs.mjs bundle that /materia:init writes into a
// user repo). Layers:
//  1. Materialization sim: copy plugins/materia/scaffold/ into the post-init
//     user-repo layout (docs/ + root CLAUDE.md/MATERIA.md + the standards stubs
//     /materia:init generates) and run check-docs.mjs over it. Skills are NOT
//     copied — installed plugins run from the read-only cache, not from
//     .claude/skills/ in the user repo — so a scaffold doc that still LINKS into
//     a skill file now fails here honestly (nothing masks it).
//  1c. Direct skills link/anchor check: resolves every relative link + #anchor
//     in plugins/materia/skills/** as the files sit in the repo (the coverage
//     the skill-free sim gives up), skipping ${CLAUDE_PLUGIN_ROOT} runtime paths
//     and http(s)/mailto links (not repo-relative). A link that escapes the
//     skills subtree fails — such refs must be repo-relative backtick prose.
//  2. § audit: every segment of every `MATERIA.md § A § B` reference chain
//     across plugins/materia/ names a real heading in MATERIA.md, plus mirror
//     pins (§ Skill routing rows that must carry an equal tier).
//  3. Slot hygiene: {{slot}} markers may exist only in the slotted templates
//     (MATERIA.md, CLAUDE.md, docs skeleton) — never in skills.
// Exits non-zero with the failures listed. Run: node scripts/validate-plugin.mjs
import { cpSync, mkdirSync, mkdtempSync, rmSync, writeFileSync, readFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join, resolve, dirname, relative, sep } from 'node:path'
import { tmpdir } from 'node:os'
import { spawnSync } from 'node:child_process'

process.chdir(join(import.meta.dirname, '..'))
let failures = 0
const fail = (msg) => { console.error(`  ✗ ${msg}`); failures++ }

// ---- 1. materialization sims + check-docs ----------------------------------
// Model the REAL /materia:init output: copy plugins/materia/scaffold/ into a
// user-repo layout (docs/ + check-docs.mjs + root CLAUDE.md/MATERIA.md, plus the
// standards stubs init always generates), then run check-docs over it. Skills
// are NOT copied and init no longer prunes — installed plugins run from the
// read-only cache, so the user repo has no .claude/skills/ at all. That makes
// the green signal HONEST: a scaffold doc that still links into a skill file
// dangles here (Part B mask removed). The two profiles differ only in which
// standards stubs get written (a UI repo adds visual-language + ui-components).
const runSim = (label, { standards }) => {
  const sim = mkdtempSync(join(tmpdir(), 'materia-sim-'))
  try {
    mkdirSync(join(sim, 'scripts'), { recursive: true })
    cpSync('plugins/materia/scaffold/docs', join(sim, 'docs'), { recursive: true })
    cpSync('plugins/materia/scaffold/scripts/check-docs.mjs', join(sim, 'scripts/check-docs.mjs'))
    cpSync('plugins/materia/scaffold/CLAUDE.md', join(sim, 'CLAUDE.md'))
    cpSync('plugins/materia/scaffold/MATERIA.md', join(sim, 'MATERIA.md'))
    // .materia/ (review-angles etc.) is intentionally NOT copied into the sim:
    // check-docs' ROOTS (['CLAUDE.md','docs']) exclude it by design, so leaving
    // it out keeps this block an honest model of what init materializes + what
    // check-docs actually scans. Registry↔angle-file drift is guarded by the
    // dedicated review-angle checks below, not by this sim.
    for (const f of standards)
      writeFileSync(join(sim, `docs/standards/${f}.md`), '# stub — generated by /materia:init\n')
    const r = spawnSync('node', ['scripts/check-docs.mjs'], { cwd: sim, encoding: 'utf8' })
    if (r.status !== 0) {
      fail(`materialization sim (${label}) failed check-docs:`)
      console.error(r.stdout + r.stderr)
    } else {
      console.log(`  ✓ materialization sim (${label}): ` + (r.stdout.trim().split('\n').pop() ?? 'clean'))
    }
  } finally {
    rmSync(sim, { recursive: true, force: true })
  }
}
runSim('UI repo', { standards: ['architecture', 'testing', 'workflow', 'visual-language', 'ui-components'] })
runSim('non-UI repo', { standards: ['architecture', 'testing', 'workflow'] })

// ---- 1c. direct skills link/anchor check ------------------------------------
// The skill-free sim (above) no longer covers skill-internal markdown links or
// anchors. Restore that coverage HONESTLY: resolve every relative link + #anchor
// in plugins/materia/skills/** exactly as the files sit in the repo — no temp
// reconstruction. Valid skill links stay inside the skills subtree: sibling
// ../<skill>/SKILL.md and intra-skill resources/... paths. ${CLAUDE_PLUGIN_ROOT}
// runtime paths (Part A's rerouted cache reads) and http(s)/mailto links are
// skipped — not repo-relative — and link syntax inside code fences / inline code
// is illustrative, not a real link. A link that ESCAPES plugins/materia/skills/**
// (e.g. a stale ../../../docs/... pointer into the user repo) FAILS: an installed
// skill runs from a read-only cache that can't reach the user repo, so such
// references must be repo-relative backtick prose, not live links.
{
  const FENCE = /```[\s\S]*?```|~~~[\s\S]*?~~~/g
  const INLINE_CODE = /`[^`]*`/g
  const LINK = /\[(?:[^[\]]|\[[^\]]*\])*\]\(([^)]+)\)/g
  const blankOut = (t, re) => t.replace(re, (m) => m.replace(/[^\n]/g, ' '))
  const slugify = (h) =>
    h.toLowerCase().replace(/`/g, '').replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/[^\w\s-]/g, '').trim().replace(/[\s-]+/g, '-')
  const slugCache = new Map()
  const slugsFor = (file) => {
    if (!slugCache.has(file)) {
      const set = new Set()
      for (const m of blankOut(readFileSync(file, 'utf8'), FENCE).matchAll(/^#{1,6}\s+(.+)$/gm)) {
        const base = slugify(m[1])
        set.add(set.has(base) ? `${base}-${[...set].filter((s) => s.startsWith(base)).length}` : base)
        set.add(base)
      }
      slugCache.set(file, set)
    }
    return slugCache.get(file)
  }
  const skillsRoot = resolve('plugins/materia/skills')
  const skillDocs = []
  const walkSkills = (p) => {
    for (const e of readdirSync(p)) {
      const fp = join(p, e)
      if (statSync(fp).isDirectory()) walkSkills(fp)
      else if (fp.endsWith('.md')) skillDocs.push(fp)
    }
  }
  walkSkills(skillsRoot)
  const before = failures
  let checked = 0
  for (const f of skillDocs.sort()) {
    const text = blankOut(blankOut(readFileSync(f, 'utf8'), FENCE), INLINE_CODE)
    for (const m of text.matchAll(LINK)) {
      const [target, fragment] = m[1].split('#')
      const path = target.trim()
      if (/^(https?:|mailto:)/.test(path)) continue
      if (path.includes('CLAUDE_PLUGIN_ROOT')) continue // runtime cache token, not repo-relative
      const resolved = path ? resolve(dirname(f), path) : resolve(f)
      if (resolved !== skillsRoot && !resolved.startsWith(skillsRoot + sep)) {
        fail(`skills link escapes plugins/materia/skills/**: ${relative(skillsRoot, f)} -> ${m[1]} — make it repo-relative backtick prose`)
        continue
      }
      if (path && !existsSync(resolved)) {
        fail(`skills link: ${relative(skillsRoot, f)} -> ${m[1]}`)
        continue
      }
      checked++
      if (fragment !== undefined && resolved.endsWith('.md')) {
        const want = fragment.trim().toLowerCase().replace(/[\s-]+/g, '-')
        const slugs = slugsFor(resolved)
        if (!slugs.has(want) && !slugs.has(want.replace(/-\d+$/, '')))
          fail(`skills anchor: ${relative(skillsRoot, f)} -> ${m[1]} (no heading matches #${fragment})`)
      }
    }
  }
  if (failures === before)
    console.log(`  ✓ direct skills link/anchor check: ${checked} links/anchors across ${skillDocs.length} skill docs resolve (natural repo layout)`)
}

// ---- 1b. stage-numbering canon ----------------------------------------------
// The status templates are the source of truth; skills that hard-code a row
// number must agree. Both sides are pinned here so drift fails CI.
const canon = [
  ['plugins/materia/scaffold/docs/specs/_templates/status.md', '- [ ] 4. architecture'],
  ['plugins/materia/scaffold/docs/specs/_templates/status.md', '- [ ] 5. plan-tasks'],
  ['plugins/materia/scaffold/docs/specs/_templates/status.md', '- [ ] 9. finalize'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 3. plan-tasks'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 6. docs-sync'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 7. docs-audit'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 8. finalize'],
  ['plugins/materia/skills/architecture/SKILL.md', 'tick stage 4 in `STATUS.md`'],
  ['plugins/materia/skills/plan-tasks/SKILL.md', 'tick stage 5 in `STATUS.md`'],
  ['plugins/materia/skills/finalize/SKILL.md', 'row 9 in the spec template, row 8 in the bug template'],
  ['plugins/materia/skills/fix-bug/SKILL.md', 'Tick **stage 3**, not stage 5'],
  ['plugins/materia/skills/fix-bug/SKILL.md', '7. **docs-audit**'],
]
for (const [f, needle] of canon)
  if (!readFileSync(f, 'utf8').includes(needle)) fail(`stage canon: ${f} missing expected text: "${needle}"`)
console.log(`  ✓ stage-numbering canon: ${canon.length} pins hold`)

// ---- 1d. § Version control citation pin -------------------------------------
// Git/forge portability (trunk, remote, baseline, and the PR/CI forge flow) is
// no longer hardcoded in the skills — it resolves from MATERIA.md § Version
// control (+ its § Forge subsection). Guard that the config home exists AND that
// every skill which resolves trunk/remote/forge AT RUNTIME actually references
// it, so a future edit can't silently re-hardcode a literal without also
// dropping the pin. This is PRESENCE + CITATION only (no denylist scan for the
// literals themselves — that was a deliberate scoping decision); the honesty of
// the swap is carried by review, this pin catches the section being renamed away
// or a listed skill losing its reference.
//
// The citation set is the skills that run trunk/remote/forge git/PR commands.
// EXCLUDED by design: `init` (it MATERIALIZES MATERIA.md — it writes this section
// from the repo's existing default branch and must not cite the config it
// writes), and `docs-sync`/`docs-audit` (they are HANDED the branch diff and run
// no git of their own — they may mention § Version control but are not required
// to). The shared producer-lifecycle standard docs/standards/skills.md IS pinned:
// the producers inherit their PR-open/branch rules from it.
//
// The match mirrors the § audit's normalization (whitespace-collapsed text +
// an optional backtick/quote after `MATERIA.md`) so a citation that wraps across
// lines or is written `MATERIA.md`\n§ Version control is not a false failure.
{
  const before = failures
  const matSrc = readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8')
  const matLines = matSrc.split('\n').map((l) => l.trimEnd())
  for (const h of ['## Version control', '### Forge'])
    if (!matLines.includes(h))
      fail(`§ Version control pin: plugins/materia/scaffold/MATERIA.md is missing the \`${h}\` heading — it is the config home the pipeline resolves trunk/remote/forge from`)
  const cites = (file) => /MATERIA\.md[`"']?\s*§\s*Version control/.test(readFileSync(file, 'utf8').replace(/\s+/g, ' '))
  const VC_CITERS = [
    'janitor', 'librarian', 'ship-spec', 'finalize', 'propose-spec', 'propose-epic',
    'report-bug', 'reconcile-epic', 'ui-inspection', 'triage-retros', 'fix-bug',
  ]
  for (const s of VC_CITERS) {
    const f = `plugins/materia/skills/${s}/SKILL.md`
    if (!existsSync(f)) { fail(`§ Version control pin: ${f} not found`); continue }
    if (!cites(f))
      fail(`§ Version control pin: ${s}/SKILL.md does not cite \`MATERIA.md § Version control\` — it resolves trunk/remote/forge at runtime and must reference the config home (not re-hardcode main/origin)`)
  }
  if (!cites('plugins/materia/scaffold/docs/standards/skills.md'))
    fail('§ Version control pin: docs/standards/skills.md does not cite `MATERIA.md § Version control` — the shared producer-lifecycle rule routes trunk/remote/forge through the config home')
  if (failures === before)
    console.log(`  ✓ § Version control citation pin: 2 headings + ${VC_CITERS.length} skills + skills.md reference the config home`)
}

// ---- helpers ---------------------------------------------------------------
const mdFiles = []
const walk = (p) => {
  for (const e of readdirSync(p)) {
    const fp = join(p, e)
    if (statSync(fp).isDirectory()) walk(fp)
    else if (fp.endsWith('.md')) mdFiles.push(fp)
  }
}
walk('plugins/materia')

// ---- 2. § audit -------------------------------------------------------------
// Every segment of a `MATERIA.md § A § B` chain must name a real heading AND,
// past the first, be a subsection of its predecessor — so a mis-scoped pointer
// like `§ Gate § Model set` (Model set is a child of Tiers, not Gate) fails,
// not just an unknown segment. References wrap across lines, so audit over
// whitespace-normalized text and match each segment against the known heading
// set (longest first, at a word boundary) rather than guessing terminators —
// which also stops the capture from swallowing trailing prose.
const heads = []
const parentOf = new Map() // h3 heading -> its parent h2, for the nesting check
let curH2 = null
for (const ln of readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8').split('\n')) {
  const m2 = /^## (.+)$/.exec(ln), m3 = /^### (.+)$/.exec(ln)
  if (m2) { curH2 = m2[1].trim(); heads.push(curH2) }
  else if (m3) { const h = m3[1].trim(); heads.push(h); if (curH2) parentOf.set(h, curH2) }
}
const headsByLen = [...heads].sort((a, b) => b.length - a.length)
// the known heading that `text` begins with (word-boundary terminated), or null
const leadingHead = (text) =>
  headsByLen.find((h) => text === h || (text.startsWith(h) && /[^A-Za-z0-9]/.test(text[h.length]))) ?? null
let refs = 0
for (const f of mdFiles) {
  const norm = readFileSync(f, 'utf8').replace(/\s+/g, ' ')
  for (const start of norm.matchAll(/MATERIA\.md[`"']?/g)) {
    let pos = start.index + start[0].length
    let prev = null
    let sm
    while ((sm = /^\s*§\s*/.exec(norm.slice(pos)))) {
      const after = pos + sm[0].length
      if (!/^[A-Za-z]/.test(norm.slice(after))) break // `§` not followed by a name → not a section ref
      pos = after
      refs++
      const h = leadingHead(norm.slice(pos))
      if (!h) {
        const bad = norm.slice(pos, pos + 30).replace(/[.,;()`|<>—'"].*$/, '').trim()
        fail(`${f}: MATERIA.md § "${bad}…" has no matching heading in plugins/materia/scaffold/MATERIA.md`)
        break // chain integrity is lost past an unknown segment
      }
      if (prev && parentOf.get(h) !== prev) {
        fail(`${f}: MATERIA.md § "${prev} § ${h}" — "${h}" is not a subsection of "${prev}"`)
        break
      }
      prev = h
      pos += h.length
    }
  }
}
console.log(`  ✓ § audit: ${refs} MATERIA.md § references (nested, all chain segments) checked against ${heads.length} headings`)

// ---- 2b. mirror pins --------------------------------------------------------
// A cross-table pin: the § Skill routing `ui-review` row governs standalone
// invocation of the skill, while the ship-spec UI review angle spawns at the
// `ui` Tier in § Review angles. The two must stay in sync, so the skill row's
// model/effort is pinned equal to the registry row's Tier here — an edit to one
// that misses the other fails CI. The registry Tier is a single `<model>/<effort>`
// pair with NO Fallback token, so this compares model+effort only (per-token
// backticks stripped on both sides so `opus` and `` `opus` `` can't mismatch).
const stripTicks = (s) => s.replace(/`/g, '').trim()
const routingRow = (label) => {
  const src = readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8')
  const re = new RegExp(`^\\|\\s*\`${label.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}\`\\s*\\|(.+)$`, 'm')
  const m = src.match(re)
  if (!m) return null
  return m[1].split('|').slice(0, 3).map((c) => c.trim()) // [Model, Effort, Fallback Model]
}
// Parse a § Review angles registry row (columns Angle | File | Gate | Tier) and
// return its Tier as a 2-token [model, effort] (backticks stripped). The
// registry Tier carries no Fallback token — hence the 2-token shape.
const registryRow = (angle) => {
  const src = readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8')
  const re = new RegExp(`^\\|\\s*\`${angle.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}\`\\s*\\|[^|]*\\|[^|]*\\|([^|]*)\\|`, 'm')
  const m = src.match(re)
  if (!m) return null
  return stripTicks(m[1]).split('/').map((t) => t.trim()) // Tier -> [model, effort]
}
const MIRRORS = [['ui-review', 'ui']]
for (const [skill, angle] of MIRRORS) {
  const rs = routingRow(skill), rg = registryRow(angle)
  if (!rs) fail(`mirror pin: § Skill routing row \`${skill}\` not found`)
  else if (!rg) fail(`mirror pin: § Review angles registry row \`${angle}\` not found`)
  else {
    const skillTier = rs.slice(0, 2).map(stripTicks) // [model, effort], backticks off
    if (skillTier.join('/') !== rg.join('/'))
      fail(`mirror pin: § Skill routing \`${skill}\` (${skillTier.join('/')}) and § Review angles \`${angle}\` Tier (${rg.join('/')}) must carry the same model/effort`)
  }
}
console.log(`  ✓ mirror pins: ${MIRRORS.length} cross-table mirror(s) hold`)

// ---- 2c. UI self-gate registry + placement ----------------------------------
// init no longer prunes skills — the four UI skills install in EVERY repo,
// including no-UI ones. Each MUST carry a runtime self-gate that exits cleanly
// when MATERIA.md § Surface gates § UI-affecting is `none`, and — most safety-
// critically for ui-inspection — that gate must run BEFORE the liveness
// probe / autostart so a no-UI repo never starts the dev stack. Presence alone
// is too weak (a gutted or relocated gate that kept the heading would pass), so
// this pins BOTH a distinctive marker AND placement:
//  - Marker: the bold gate lead-in `**UI self-gate` — a prose mention of "UI
//    self-gate" (e.g. design's § Scope) is NOT bolded, so it can never
//    satisfy the check (closes the accidental word-wrap false-green).
//  - Placement: the marker's offset must precede the skill's first side-effect
//    anchor. For ui-inspection that anchor IS the liveness/autostart
//    step, mechanically enforcing "gate before autostart"; for the other three
//    it is the first provisioning/read/short-circuit, enforcing "gate first".
// Repurposes the former UI_PRUNE set (skill → first-side-effect anchor).
const GATE_MARKER = '**UI self-gate'
const UI_SELF_GATE = {
  'design': 'docs/specs/_templates/design.md',            // step 1: first spec read
  'ui-test-plan': 'Pure non-behavioral change',           // the zero-flow waiver short-circuit (first write)
  'ui-review': 'Provision the Eyes environment',          // step 1: Eyes provisioning
  'ui-inspection': 'Probe the running app for liveness',  // Phase 0 step 1: liveness probe / autostart
}
const gateBefore = failures
for (const [skill, anchor] of Object.entries(UI_SELF_GATE)) {
  const s = readFileSync(`plugins/materia/skills/${skill}/SKILL.md`, 'utf8')
  const mark = s.indexOf(GATE_MARKER)
  const side = s.indexOf(anchor)
  if (mark === -1)
    fail(`UI self-gate: ${skill}/SKILL.md is missing the "${GATE_MARKER}" gate marker — it installs in every repo and must exit cleanly when MATERIA.md § UI-affecting is none`)
  else if (side === -1)
    fail(`UI self-gate: ${skill}/SKILL.md placement anchor "${anchor}" not found — cannot verify the gate runs before the first side-effect (did the anchor text change?)`)
  else if (mark > side)
    fail(`UI self-gate: ${skill}/SKILL.md gate marker is AFTER "${anchor}" — the gate must run before the first side-effect (for ui-inspection, before the liveness probe / autostart) or a no-UI repo acts before it self-gates`)
}
if (failures === gateBefore)
  console.log(`  ✓ UI self-gate: ${Object.keys(UI_SELF_GATE).length} UI skills carry the "${GATE_MARKER}" gate before their first side-effect`)

// ---- 2d. skill ↔ § Skill routing coverage -----------------------------------
// init no longer prunes, so EVERY skill dir ships in every repo, and each must
// be accounted for in MATERIA.md § Skill routing exactly once — via a plain row
// (label == dir) XOR the "Operator-session skills (rowless by design)" list. A
// future skill added with neither is the F3 gap this guards: it would silently
// fall to the Default row with no operator ever having sized it. Role rows
// (`<skill>: <role>`) account for an internal role only, never the parent dir —
// so a role-row parent (`janitor`, `ship-spec`, …) is covered by its LIST entry,
// not its role row, and that is not a double-count. We parse ONLY the § Skill
// routing section slice (bounded by its h3 and the next ##/### — the operator-
// session #### h4 stays inside it, and its bullets aren't `|`-rows) and the
// operator-session list slice separately, so no rows from § Review angles /
// § Model set can leak in.
{
  const before = failures
  const src = readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8')
  const lines = src.split('\n')
  // Slice § Skill routing: from its h3 to the next ##/### (a #### h4 — the
  // operator-session subheading — does NOT terminate the slice).
  let secStart = -1, secEnd = lines.length
  for (let i = 0; i < lines.length; i++) {
    if (/^### Skill routing\s*$/.test(lines[i])) { secStart = i; continue }
    if (secStart !== -1 && /^#{2,3} /.test(lines[i])) { secEnd = i; break }
  }
  if (secStart === -1) fail('skill↔routing: MATERIA.md has no `### Skill routing` section')
  const routing = secStart === -1 ? '' : lines.slice(secStart, secEnd).join('\n')
  // Table-row labels: first cell, backtick-wrapped. The `**Default** …` row is
  // not backticked, so it never matches (correct). Classify each label:
  // `a: b` → role row, parent `a`; else plain row, the label IS a skill name.
  const plainRows = new Set(), roleParents = new Set(), rowLabels = []
  for (const ln of routing.split('\n')) {
    const m = /^\|\s*`([^`]+)`/.exec(ln)
    if (!m) continue
    const label = m[1].trim()
    rowLabels.push(label)
    if (label.includes(': ')) roleParents.add(label.split(': ')[0].trim())
    else plainRows.add(label)
  }
  // Slice the operator-session list: from its exact #### h4 to the next heading
  // of any level; each bullet's first backticked token is a rowless-by-design
  // skill name.
  let listStart = -1, listEnd = lines.length
  for (let i = 0; i < lines.length; i++) {
    if (/^#### Operator-session skills \(rowless by design\)\s*$/.test(lines[i])) { listStart = i; continue }
    if (listStart !== -1 && /^#{1,6} /.test(lines[i])) { listEnd = i; break }
  }
  if (listStart === -1) fail('skill↔routing: MATERIA.md has no `#### Operator-session skills (rowless by design)` list')
  const opList = new Set()
  for (const ln of (listStart === -1 ? [] : lines.slice(listStart + 1, listEnd))) {
    const m = /^-\s*`([^`]+)`/.exec(ln)
    if (m) opList.add(m[1].trim())
  }
  // Skill dirs shipped under plugins/materia/skills/.
  const skillDirs = readdirSync('plugins/materia/skills', { withFileTypes: true })
    .filter((e) => e.isDirectory()).map((e) => e.name)
  const dirSet = new Set(skillDirs)
  // A. Coverage — each dir accounted by EXACTLY ONE of {plain row} XOR {list}.
  for (const d of skillDirs) {
    const hasRow = plainRows.has(d), inList = opList.has(d)
    if (!hasRow && !inList)
      fail(`skill \`${d}\` is unaccounted in MATERIA.md § Skill routing — add a plain row, or list it under 'Operator-session skills (rowless by design)'`)
    else if (hasRow && inList)
      fail(`skill \`${d}\` is double-accounted (has a plain row AND is in the operator-session list) — pick one`)
  }
  // B. Orphan-row hygiene — every plain label + every role-row parent is a dir.
  for (const name of [...plainRows, ...roleParents])
    if (!dirSet.has(name))
      fail(`§ Skill routing row \`${name}\` names no skill dir under plugins/materia/skills/`)
  // C. Operator-session list hygiene — every listed name is a real dir.
  for (const name of opList)
    if (!dirSet.has(name))
      fail(`§ Skill routing operator-session list entry \`${name}\` names no skill dir under plugins/materia/skills/`)
  // Canon pin (consistency anchor): every `<skill>: <role>` row must be cited by
  // its exact backticked label in that skill's SKILL.md. Routing resolves from
  // this table regardless, but the prose citation is what keeps a maintainer
  // sizing the spawn here — an uncited role row is the drift that lets a future
  // edit relocate the spawn and silently pick up the Default row. Guards every
  // role row, not just janitor's. (Boundary: this covers skill dirs and cited
  // role rows — a future internal role added with no row at all is not a dir and
  // has no label, so it stays outside the mechanical guarantee; check A + the
  // operator-session list close the skill-dir case, which is the guarded one.)
  for (const label of rowLabels) {
    if (!label.includes(': ')) continue
    const parent = label.split(': ')[0].trim()
    if (!dirSet.has(parent)) continue // orphan parent already reported by check B
    const skillFile = `plugins/materia/skills/${parent}/SKILL.md`
    if (!existsSync(skillFile)) { fail(`${parent}/ has no SKILL.md — cannot verify it cites its \`${label}\` routing row`); continue }
    if (!readFileSync(skillFile, 'utf8').includes('`' + label + '`'))
      fail(`${parent}/SKILL.md does not cite its \`${label}\` routing row — a spawned role left uncited can drift to the Default row`)
  }
  if (failures === before)
    console.log(`  ✓ skill↔routing coverage: ${skillDirs.length} skill dirs each accounted (plain row XOR operator-session list); ${rowLabels.length + opList.size} rows/list entries name real skills`)
}

// ---- 3. slot hygiene ---------------------------------------------------------
// Skills ship slot-free (slots live in MATERIA.md/CLAUDE.md/docs). Rule is
// pattern-scoped, not file-scoped: flag a `{{` only when it is NOT immediately
// preceded by a backtick. A backtick-quoted `{{slot}}` is documentation of the
// slot-filling mechanism (init describes it), never a shipped unfilled
// marker — so it's allowed, while a bare pasted `{{...}}` still fails, in every
// skill including init.
for (const f of mdFiles.filter((f) => f.includes('plugins/materia/skills/'))) {
  const s = readFileSync(f, 'utf8')
  for (let i = s.indexOf('{{'); i !== -1; i = s.indexOf('{{', i + 2)) {
    if (i === 0 || s[i - 1] !== '`') {
      fail(`${f} carries an unquoted {{slot}} marker at offset ${i} — skills ship slot-free (a backtick-quoted \`{{slot}}\` documentation mention is allowed)`)
      break
    }
  }
}
console.log('  ✓ slot hygiene: no unquoted {{slot}} markers in skills')

// ---- 4. review-angle registry ↔ file bijection + front-matter conformance ---
// Review angles are a materialized library: one file per angle under
// plugins/materia/scaffold/.materia/review-angles/, and MATERIA.md § Review
// angles (columns Angle | File | Gate | Tier) is the registry. The user repo's
// materialized .materia/ is NOT check-docs-scanned, so THIS is the only
// mechanical guard against registry↔file drift. Pins a strict bijection plus
// front-matter conformance:
//  - every registry row's File names an existing angle file;
//  - every angle file (except README.md) has exactly one registry row — no
//    orphan file, no duplicate rows for one file;
//  - each row's Angle slug equals its File stem;
//  - each angle file carries `---`…`---` YAML front matter whose ONLY keys are
//    `name` + `description`, with name == filename stem (transitively == the
//    registry Angle slug) and a non-empty description. A stray gate:/tier:/
//    category: key is the exact "gate lives in the registry, not the file"
//    violation and fails here.
const ANGLE_DIR = 'plugins/materia/scaffold/.materia/review-angles'
{
  const before = failures
  const src = readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8')
  // Slice the ## Review angles section body so we parse ONLY its registry table
  // (the § Skill routing table also has `slug` | `value` rows we must not read).
  const lines = src.split('\n')
  let start = -1, end = lines.length
  for (let i = 0; i < lines.length; i++) {
    if (/^## Review angles\s*$/.test(lines[i])) start = i
    else if (start !== -1 && /^## /.test(lines[i])) { end = i; break }
  }
  const section = start === -1 ? '' : lines.slice(start, end).join('\n')
  if (start === -1) fail('review-angle registry: MATERIA.md has no `## Review angles` section')
  // Registry data rows: | `angle` | `file` | ... | (header/separator have no
  // backticks). Fail CLOSED: any table row in the slice that is not the header
  // or separator MUST have backticked Angle+File cells — a bare row (e.g. a
  // hand-appended `| a11y | a11y.md | … |`) would otherwise be silently skipped,
  // escaping every check below (the exact drift this guard exists to catch).
  const rows = []
  for (const ln of section.split('\n')) {
    if (!/^\|/.test(ln)) continue // not a table row
    if (/^\|\s*-+\s*\|/.test(ln)) continue // separator |---|---|
    if (/^\|\s*Angle\s*\|/.test(ln)) continue // header
    const m = /^\|\s*`([^`]+)`\s*\|\s*`([^`]+)`\s*\|/.exec(ln)
    if (!m) { fail(`review-angle registry: malformed row "${ln.trim()}" — the Angle and File cells must be backticked (\`slug\` | \`slug.md\`)`); continue }
    rows.push({ angle: m[1].trim(), file: m[2].trim() })
  }
  const angleFiles = readdirSync(ANGLE_DIR).filter((f) => f.endsWith('.md') && f !== 'README.md')
  const rowsByFile = new Map()
  for (const row of rows) {
    const stem = row.file.replace(/\.md$/, '')
    if (row.angle !== stem)
      fail(`review-angle registry: row Angle \`${row.angle}\` does not match its File stem \`${stem}\` — the Angle slug must equal the filename stem`)
    if (!existsSync(join(ANGLE_DIR, row.file)))
      fail(`review-angle registry: row \`${row.angle}\` names File \`${row.file}\` but ${ANGLE_DIR}/${row.file} does not exist`)
    if (!rowsByFile.has(row.file)) rowsByFile.set(row.file, [])
    rowsByFile.get(row.file).push(row.angle)
  }
  for (const [file, angles] of rowsByFile)
    if (angles.length > 1)
      fail(`review-angle registry: File \`${file}\` is named by ${angles.length} registry rows (${angles.join(', ')}) — exactly one row per file`)
  for (const f of angleFiles)
    if (!rowsByFile.has(f))
      fail(`review-angle registry: ${ANGLE_DIR}/${f} has no § Review angles row — every angle file needs exactly one registry row`)
  // Front-matter conformance, per angle file on disk.
  for (const f of angleFiles.sort()) {
    const stem = f.replace(/\.md$/, '')
    const raw = readFileSync(join(ANGLE_DIR, f), 'utf8')
    const fm = /^---\n([\s\S]*?)\n---/.exec(raw)
    if (!fm) {
      fail(`review-angle front matter: ${ANGLE_DIR}/${f} has no \`---\`…\`---\` YAML front matter (needs name + description)`)
      continue
    }
    const keys = new Map()
    for (const ln of fm[1].split('\n')) {
      if (!ln.trim()) continue
      if (/^\s/.test(ln)) continue // indented YAML continuation (folded/block scalar) — not a key
      const kv = /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/.exec(ln)
      if (!kv) { fail(`review-angle front matter: ${ANGLE_DIR}/${f} has a non key:value front-matter line: "${ln.trim()}"`); continue }
      keys.set(kv[1], kv[2].trim())
    }
    const extra = [...keys.keys()].filter((k) => k !== 'name' && k !== 'description')
    if (extra.length)
      fail(`review-angle front matter: ${ANGLE_DIR}/${f} has disallowed front-matter key(s) ${extra.map((k) => `\`${k}\``).join(', ')} — only \`name\` and \`description\` are allowed (Gate/Tier live in the § Review angles registry, not the file)`)
    if (!keys.has('name'))
      fail(`review-angle front matter: ${ANGLE_DIR}/${f} is missing the \`name\` key`)
    else if (keys.get('name') !== stem)
      fail(`review-angle front matter: ${ANGLE_DIR}/${f} has name \`${keys.get('name')}\` but must equal its filename stem \`${stem}\``)
    if (!keys.has('description') || !keys.get('description'))
      fail(`review-angle front matter: ${ANGLE_DIR}/${f} is missing a non-empty \`description\``)
  }
  if (failures === before)
    console.log(`  ✓ review-angle registry: ${rows.length} rows ↔ ${angleFiles.length} files (bijection; Angle==File stem==name; name+description only)`)
}

// ---- 5. review-angle slot + link hygiene ------------------------------------
// The skills-only slot scan (§3) and direct-skills link check (§1c) both filter
// to plugins/materia/skills/, so a {{slot}} or a live [text](path) link in a
// verbatim-shipped angle file went uncaught. Angle files ship byte-for-byte via
// /materia:init, so hold them to the same hygiene: no unquoted {{slot}} markers,
// no live markdown links to repo-relative paths (backtick prose only; http(s)/
// mailto and ${CLAUDE_PLUGIN_ROOT} are exempt, mirroring §1c). Live-link syntax
// inside code fences or inline code is illustrative — blanked before the link
// scan. The {{slot}} scan follows §3's rule instead (a bare {{ fails unless
// backtick-adjacent; fences are NOT exempt), so it runs over the raw text.
{
  const FENCE = /```[\s\S]*?```|~~~[\s\S]*?~~~/g
  const INLINE_CODE = /`[^`]*`/g
  const LINK = /\[(?:[^[\]]|\[[^\]]*\])*\]\(([^)]+)\)/g
  const blankOut = (t, re) => t.replace(re, (m) => m.replace(/[^\n]/g, ' '))
  const before = failures
  const files = readdirSync(ANGLE_DIR).filter((f) => f.endsWith('.md')).sort()
  for (const f of files) {
    const raw = readFileSync(join(ANGLE_DIR, f), 'utf8')
    // Slot hygiene: same rule as §3 — a bare `{{` fails, a backtick-quoted
    // `{{slot}}` documentation mention is allowed.
    for (let i = raw.indexOf('{{'); i !== -1; i = raw.indexOf('{{', i + 2)) {
      if (i === 0 || raw[i - 1] !== '`') {
        fail(`review-angle slot hygiene: ${ANGLE_DIR}/${f} carries an unquoted {{slot}} marker at offset ${i} — angle files ship verbatim and must be slot-free (a backtick-quoted \`{{slot}}\` mention is allowed)`)
        break
      }
    }
    // Link hygiene: scan with fences + inline code blanked out.
    const code = blankOut(blankOut(raw, FENCE), INLINE_CODE)
    for (const m of code.matchAll(LINK)) {
      const path = m[1].split('#')[0].trim()
      if (/^(https?:|mailto:)/.test(path)) continue
      if (path.includes('CLAUDE_PLUGIN_ROOT')) continue // runtime cache token, not repo-relative
      fail(`review-angle link hygiene: ${ANGLE_DIR}/${f} has a live markdown link \`${m[0].trim()}\` — angle files must use backtick prose for repo-relative paths, not live links`)
    }
  }
  if (failures === before)
    console.log(`  ✓ review-angle hygiene: no unquoted {{slot}} markers or live repo-relative links in ${files.length} angle-dir files`)
}

if (failures) {
  console.error(`\n${failures} validation failure(s).`)
  process.exit(1)
}
console.log('\nplugin validation: all clean.')
