#!/usr/bin/env node
// Plugin validation — simulates what /materia-init materializes from the
// `materia` plugin's bundled scaffold, then verifies it. No network, no AI.
// The plugin lives at plugins/materia/: skills/ (all pipeline skills, at the
// plugin root per the Claude Code plugin spec) and scaffold/ (the MATERIA.md +
// CLAUDE.md + docs/ + check-docs.mjs bundle that /materia-init writes into a
// user repo). Layers:
//  1. Materialization sim: copy plugins/materia/scaffold/ into the post-init
//     user-repo layout (docs/ + root CLAUDE.md/MATERIA.md + the standards stubs
//     /materia-init generates) and run check-docs.mjs over it. Skills are NOT
//     copied — installed plugins run from the read-only cache, not from
//     .claude/skills/ in the user repo — so a scaffold doc that still LINKS into
//     a skill file now fails here honestly (nothing masks it).
//  1c. Direct skills link/anchor check: resolves every relative link + #anchor
//     in plugins/materia/skills/** as the files sit in the repo (the coverage
//     the skill-free sim gives up), skipping ${CLAUDE_PLUGIN_ROOT} runtime paths
//     and http(s)/mailto links (not repo-relative). A link that escapes the
//     skills subtree fails — such refs must be repo-relative backtick prose.
//  2. § audit: every segment of every `MATERIA.md § A § B` reference chain
//     across plugins/materia/ names a real heading in MATERIA.md, plus mirror
//     pins (§ Skill routing rows that must carry an equal tier).
//  3. Slot hygiene: {{slot}} markers may exist only in the slotted templates
//     (MATERIA.md, CLAUDE.md, docs skeleton) — never in skills.
// Exits non-zero with the failures listed. Run: node scripts/validate-plugin.mjs
import { cpSync, mkdirSync, mkdtempSync, rmSync, writeFileSync, readFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join, resolve, dirname, relative, sep } from 'node:path'
import { tmpdir } from 'node:os'
import { spawnSync } from 'node:child_process'

process.chdir(join(import.meta.dirname, '..'))
let failures = 0
const fail = (msg) => { console.error(`  ✗ ${msg}`); failures++ }

// ---- 1. materialization sims + check-docs ----------------------------------
// Model the REAL /materia-init output: copy plugins/materia/scaffold/ into a
// user-repo layout (docs/ + check-docs.mjs + root CLAUDE.md/MATERIA.md, plus the
// standards stubs init always generates), then run check-docs over it. Skills
// are NOT copied and init no longer prunes — installed plugins run from the
// read-only cache, so the user repo has no .claude/skills/ at all. That makes
// the green signal HONEST: a scaffold doc that still links into a skill file
// dangles here (Part B mask removed). The two profiles differ only in which
// standards stubs get written (a UI repo adds visual-language + ui-components).
const runSim = (label, { standards }) => {
  const sim = mkdtempSync(join(tmpdir(), 'materia-sim-'))
  try {
    mkdirSync(join(sim, 'scripts'), { recursive: true })
    cpSync('plugins/materia/scaffold/docs', join(sim, 'docs'), { recursive: true })
    cpSync('plugins/materia/scaffold/scripts/check-docs.mjs', join(sim, 'scripts/check-docs.mjs'))
    cpSync('plugins/materia/scaffold/CLAUDE.md', join(sim, 'CLAUDE.md'))
    cpSync('plugins/materia/scaffold/MATERIA.md', join(sim, 'MATERIA.md'))
    for (const f of standards)
      writeFileSync(join(sim, `docs/standards/${f}.md`), '# stub — generated by /materia-init\n')
    const r = spawnSync('node', ['scripts/check-docs.mjs'], { cwd: sim, encoding: 'utf8' })
    if (r.status !== 0) {
      fail(`materialization sim (${label}) failed check-docs:`)
      console.error(r.stdout + r.stderr)
    } else {
      console.log(`  ✓ materialization sim (${label}): ` + (r.stdout.trim().split('\n').pop() ?? 'clean'))
    }
  } finally {
    rmSync(sim, { recursive: true, force: true })
  }
}
runSim('UI repo', { standards: ['architecture', 'testing', 'workflow', 'visual-language', 'ui-components'] })
runSim('non-UI repo', { standards: ['architecture', 'testing', 'workflow'] })

// ---- 1c. direct skills link/anchor check ------------------------------------
// The skill-free sim (above) no longer covers skill-internal markdown links or
// anchors. Restore that coverage HONESTLY: resolve every relative link + #anchor
// in plugins/materia/skills/** exactly as the files sit in the repo — no temp
// reconstruction. Valid skill links stay inside the skills subtree: sibling
// ../<skill>/SKILL.md and intra-skill resources/... paths. ${CLAUDE_PLUGIN_ROOT}
// runtime paths (Part A's rerouted cache reads) and http(s)/mailto links are
// skipped — not repo-relative — and link syntax inside code fences / inline code
// is illustrative, not a real link. A link that ESCAPES plugins/materia/skills/**
// (e.g. a stale ../../../docs/... pointer into the user repo) FAILS: an installed
// skill runs from a read-only cache that can't reach the user repo, so such
// references must be repo-relative backtick prose, not live links.
{
  const FENCE = /```[\s\S]*?```|~~~[\s\S]*?~~~/g
  const INLINE_CODE = /`[^`]*`/g
  const LINK = /\[(?:[^[\]]|\[[^\]]*\])*\]\(([^)]+)\)/g
  const blankOut = (t, re) => t.replace(re, (m) => m.replace(/[^\n]/g, ' '))
  const slugify = (h) =>
    h.toLowerCase().replace(/`/g, '').replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/[^\w\s-]/g, '').trim().replace(/[\s-]+/g, '-')
  const slugCache = new Map()
  const slugsFor = (file) => {
    if (!slugCache.has(file)) {
      const set = new Set()
      for (const m of blankOut(readFileSync(file, 'utf8'), FENCE).matchAll(/^#{1,6}\s+(.+)$/gm)) {
        const base = slugify(m[1])
        set.add(set.has(base) ? `${base}-${[...set].filter((s) => s.startsWith(base)).length}` : base)
        set.add(base)
      }
      slugCache.set(file, set)
    }
    return slugCache.get(file)
  }
  const skillsRoot = resolve('plugins/materia/skills')
  const skillDocs = []
  const walkSkills = (p) => {
    for (const e of readdirSync(p)) {
      const fp = join(p, e)
      if (statSync(fp).isDirectory()) walkSkills(fp)
      else if (fp.endsWith('.md')) skillDocs.push(fp)
    }
  }
  walkSkills(skillsRoot)
  const before = failures
  let checked = 0
  for (const f of skillDocs.sort()) {
    const text = blankOut(blankOut(readFileSync(f, 'utf8'), FENCE), INLINE_CODE)
    for (const m of text.matchAll(LINK)) {
      const [target, fragment] = m[1].split('#')
      const path = target.trim()
      if (/^(https?:|mailto:)/.test(path)) continue
      if (path.includes('CLAUDE_PLUGIN_ROOT')) continue // runtime cache token, not repo-relative
      const resolved = path ? resolve(dirname(f), path) : resolve(f)
      if (resolved !== skillsRoot && !resolved.startsWith(skillsRoot + sep)) {
        fail(`skills link escapes plugins/materia/skills/**: ${relative(skillsRoot, f)} -> ${m[1]} — make it repo-relative backtick prose`)
        continue
      }
      if (path && !existsSync(resolved)) {
        fail(`skills link: ${relative(skillsRoot, f)} -> ${m[1]}`)
        continue
      }
      checked++
      if (fragment !== undefined && resolved.endsWith('.md')) {
        const want = fragment.trim().toLowerCase().replace(/[\s-]+/g, '-')
        const slugs = slugsFor(resolved)
        if (!slugs.has(want) && !slugs.has(want.replace(/-\d+$/, '')))
          fail(`skills anchor: ${relative(skillsRoot, f)} -> ${m[1]} (no heading matches #${fragment})`)
      }
    }
  }
  if (failures === before)
    console.log(`  ✓ direct skills link/anchor check: ${checked} links/anchors across ${skillDocs.length} skill docs resolve (natural repo layout)`)
}

// ---- 1b. stage-numbering canon ----------------------------------------------
// The status templates are the source of truth; skills that hard-code a row
// number must agree. Both sides are pinned here so drift fails CI.
const canon = [
  ['plugins/materia/scaffold/docs/specs/_templates/status.md', '- [ ] 4. architecture'],
  ['plugins/materia/scaffold/docs/specs/_templates/status.md', '- [ ] 5. plan-tasks'],
  ['plugins/materia/scaffold/docs/specs/_templates/status.md', '- [ ] 9. finalize'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 3. plan-tasks'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 6. docs-sync'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 7. docs-audit'],
  ['plugins/materia/scaffold/docs/bugs/_templates/status.md', '- [ ] 8. finalize'],
  ['plugins/materia/skills/materia-architecture/SKILL.md', 'tick stage 4 in `STATUS.md`'],
  ['plugins/materia/skills/materia-plan-tasks/SKILL.md', 'tick stage 5 in `STATUS.md`'],
  ['plugins/materia/skills/materia-finalize/SKILL.md', 'row 9 in the spec template, row 8 in the bug template'],
  ['plugins/materia/skills/materia-fix-bug/SKILL.md', 'Tick **stage 3**, not stage 5'],
  ['plugins/materia/skills/materia-fix-bug/SKILL.md', '7. **docs-audit**'],
]
for (const [f, needle] of canon)
  if (!readFileSync(f, 'utf8').includes(needle)) fail(`stage canon: ${f} missing expected text: "${needle}"`)
console.log(`  ✓ stage-numbering canon: ${canon.length} pins hold`)

// ---- helpers ---------------------------------------------------------------
const mdFiles = []
const walk = (p) => {
  for (const e of readdirSync(p)) {
    const fp = join(p, e)
    if (statSync(fp).isDirectory()) walk(fp)
    else if (fp.endsWith('.md')) mdFiles.push(fp)
  }
}
walk('plugins/materia')

// ---- 2. § audit -------------------------------------------------------------
// Every segment of a `MATERIA.md § A § B` chain must name a real heading AND,
// past the first, be a subsection of its predecessor — so a mis-scoped pointer
// like `§ Gate § Model set` (Model set is a child of Tiers, not Gate) fails,
// not just an unknown segment. References wrap across lines, so audit over
// whitespace-normalized text and match each segment against the known heading
// set (longest first, at a word boundary) rather than guessing terminators —
// which also stops the capture from swallowing trailing prose.
const heads = []
const parentOf = new Map() // h3 heading -> its parent h2, for the nesting check
let curH2 = null
for (const ln of readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8').split('\n')) {
  const m2 = /^## (.+)$/.exec(ln), m3 = /^### (.+)$/.exec(ln)
  if (m2) { curH2 = m2[1].trim(); heads.push(curH2) }
  else if (m3) { const h = m3[1].trim(); heads.push(h); if (curH2) parentOf.set(h, curH2) }
}
const headsByLen = [...heads].sort((a, b) => b.length - a.length)
// the known heading that `text` begins with (word-boundary terminated), or null
const leadingHead = (text) =>
  headsByLen.find((h) => text === h || (text.startsWith(h) && /[^A-Za-z0-9]/.test(text[h.length]))) ?? null
let refs = 0
for (const f of mdFiles) {
  const norm = readFileSync(f, 'utf8').replace(/\s+/g, ' ')
  for (const start of norm.matchAll(/MATERIA\.md[`"']?/g)) {
    let pos = start.index + start[0].length
    let prev = null
    let sm
    while ((sm = /^\s*§\s*/.exec(norm.slice(pos)))) {
      const after = pos + sm[0].length
      if (!/^[A-Za-z]/.test(norm.slice(after))) break // `§` not followed by a name → not a section ref
      pos = after
      refs++
      const h = leadingHead(norm.slice(pos))
      if (!h) {
        const bad = norm.slice(pos, pos + 30).replace(/[.,;()`|<>—'"].*$/, '').trim()
        fail(`${f}: MATERIA.md § "${bad}…" has no matching heading in plugins/materia/scaffold/MATERIA.md`)
        break // chain integrity is lost past an unknown segment
      }
      if (prev && parentOf.get(h) !== prev) {
        fail(`${f}: MATERIA.md § "${prev} § ${h}" — "${h}" is not a subsection of "${prev}"`)
        break
      }
      prev = h
      pos += h.length
    }
  }
}
console.log(`  ✓ § audit: ${refs} MATERIA.md § references (nested, all chain segments) checked against ${heads.length} headings`)

// ---- 2b. mirror pins --------------------------------------------------------
// Rows in § Skill routing that intentionally duplicate another row's tier are
// pinned equal here so an edit to one that misses the other fails CI.
const routingRow = (label) => {
  const src = readFileSync('plugins/materia/scaffold/MATERIA.md', 'utf8')
  const re = new RegExp(`^\\|\\s*\`${label.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}\`\\s*\\|(.+)$`, 'm')
  const m = src.match(re)
  if (!m) return null
  return m[1].split('|').slice(0, 3).map((c) => c.trim()) // [Model, Effort, Fallback Model]
}
const MIRRORS = [['materia-ui-review', 'ship-spec: review/ui']]
for (const [a, b] of MIRRORS) {
  const ra = routingRow(a), rb = routingRow(b)
  if (!ra) fail(`mirror pin: § Skill routing row \`${a}\` not found`)
  else if (!rb) fail(`mirror pin: § Skill routing row \`${b}\` not found`)
  else if (ra.join('/') !== rb.join('/'))
    fail(`mirror pin: \`${a}\` (${ra.join('/')}) and \`${b}\` (${rb.join('/')}) must carry the same tier`)
}
console.log(`  ✓ mirror pins: ${MIRRORS.length} routing-row mirror(s) hold`)

// ---- 2c. UI self-gate registry + placement ----------------------------------
// init no longer prunes skills — the four UI skills install in EVERY repo,
// including no-UI ones. Each MUST carry a runtime self-gate that exits cleanly
// when MATERIA.md § Surface gates § UI-affecting is `none`, and — most safety-
// critically for materia-ui-inspection — that gate must run BEFORE the liveness
// probe / autostart so a no-UI repo never starts the dev stack. Presence alone
// is too weak (a gutted or relocated gate that kept the heading would pass), so
// this pins BOTH a distinctive marker AND placement:
//  - Marker: the bold gate lead-in `**UI self-gate` — a prose mention of "UI
//    self-gate" (e.g. materia-design's § Scope) is NOT bolded, so it can never
//    satisfy the check (closes the accidental word-wrap false-green).
//  - Placement: the marker's offset must precede the skill's first side-effect
//    anchor. For materia-ui-inspection that anchor IS the liveness/autostart
//    step, mechanically enforcing "gate before autostart"; for the other three
//    it is the first provisioning/read/short-circuit, enforcing "gate first".
// Repurposes the former UI_PRUNE set (skill → first-side-effect anchor).
const GATE_MARKER = '**UI self-gate'
const UI_SELF_GATE = {
  'materia-design': 'docs/specs/_templates/design.md',            // step 1: first spec read
  'materia-ui-test-plan': 'Pure non-behavioral change',           // the zero-flow waiver short-circuit (first write)
  'materia-ui-review': 'Provision the Eyes environment',          // step 1: Eyes provisioning
  'materia-ui-inspection': 'Probe the running app for liveness',  // Phase 0 step 1: liveness probe / autostart
}
const gateBefore = failures
for (const [skill, anchor] of Object.entries(UI_SELF_GATE)) {
  const s = readFileSync(`plugins/materia/skills/${skill}/SKILL.md`, 'utf8')
  const mark = s.indexOf(GATE_MARKER)
  const side = s.indexOf(anchor)
  if (mark === -1)
    fail(`UI self-gate: ${skill}/SKILL.md is missing the "${GATE_MARKER}" gate marker — it installs in every repo and must exit cleanly when MATERIA.md § UI-affecting is none`)
  else if (side === -1)
    fail(`UI self-gate: ${skill}/SKILL.md placement anchor "${anchor}" not found — cannot verify the gate runs before the first side-effect (did the anchor text change?)`)
  else if (mark > side)
    fail(`UI self-gate: ${skill}/SKILL.md gate marker is AFTER "${anchor}" — the gate must run before the first side-effect (for materia-ui-inspection, before the liveness probe / autostart) or a no-UI repo acts before it self-gates`)
}
if (failures === gateBefore)
  console.log(`  ✓ UI self-gate: ${Object.keys(UI_SELF_GATE).length} UI skills carry the "${GATE_MARKER}" gate before their first side-effect`)

// ---- 3. slot hygiene ---------------------------------------------------------
// Skills ship slot-free (slots live in MATERIA.md/CLAUDE.md/docs). Rule is
// pattern-scoped, not file-scoped: flag a `{{` only when it is NOT immediately
// preceded by a backtick. A backtick-quoted `{{slot}}` is documentation of the
// slot-filling mechanism (materia-init describes it), never a shipped unfilled
// marker — so it's allowed, while a bare pasted `{{...}}` still fails, in every
// skill including materia-init.
for (const f of mdFiles.filter((f) => f.includes('plugins/materia/skills/'))) {
  const s = readFileSync(f, 'utf8')
  for (let i = s.indexOf('{{'); i !== -1; i = s.indexOf('{{', i + 2)) {
    if (i === 0 || s[i - 1] !== '`') {
      fail(`${f} carries an unquoted {{slot}} marker at offset ${i} — skills ship slot-free (a backtick-quoted \`{{slot}}\` documentation mention is allowed)`)
      break
    }
  }
}
console.log('  ✓ slot hygiene: no unquoted {{slot}} markers in skills')

if (failures) {
  console.error(`\n${failures} validation failure(s).`)
  process.exit(1)
}
console.log('\nplugin validation: all clean.')
